# Generated by Django 6.0.8 on 2026-09-04 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('president', '会長'), ('representative', '代議員')], max_length=20)),
                ('phase', models.CharField(choices=[('preliminary', '予備選挙'), ('final', '本選挙')], max_length=20)),
                ('status', models.CharField(choices=[('draft', '準備中'), ('open', '投票受付中'), ('closed', '投票終了'), ('counted', '開票済')], default='draft', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='election.electioncycle')),
            ],
            options={
                'ordering': ['cycle', 'phase', 'office'],
            },
        ),
        migrations.CreateModel(
            name='MemberSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('employee_type', models.CharField(max_length=100)),
                ('business_category', models.CharField(blank=True, max_length=100)),
                ('representative_category', models.CharField(choices=[('general', '一般枠'), ('corporate', '企業枠')], max_length=20)),
                ('is_eligible_voter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='election.electioncycle')),
            ],
            options={
                'ordering': ['member_no'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('eligible', '被選挙人'), ('qualified', '本選挙進出'), ('accepted', '立候補承諾'), ('declined', '辞退'), ('disqualified', '資格なし')], default='eligible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='election.election')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidacies', to='election.membersnapshot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='election',
            constraint=models.UniqueConstraint(fields=('cycle', 'office', 'phase'), name='unique_election_per_cycle_office_phase'),
        ),
        migrations.AddConstraint(
            model_name='membersnapshot',
            constraint=models.UniqueConstraint(fields=('cycle', 'member_no'), name='unique_member_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('election', 'member'), name='unique_candidate_per_election'),
        ),
    ]
