# Generated by Django 6.0.8 on 2026-09-09 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='election.election')),
            ],
        ),
        migrations.CreateModel(
            name='BallotChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='election.ballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballot_choices', to='election.candidate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ballot', 'candidate'), name='unique_candidate_per_ballot')],
            },
        ),
        migrations.CreateModel(
            name='VoterParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(blank=True, max_length=64)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voter_participations', to='election.election')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voter_participations', to='election.membersnapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('election', 'member'), name='unique_voter_participation')],
            },
        ),
    ]
