# Generated by Django 6.0.8 on 2026-09-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_ballot_ballotchoice_voterparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterparticipation',
            name='token_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
