# Generated by Django 6.0.8 on 2026-09-09 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_alter_voterparticipation_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('eligible', '被選挙人'), ('qualified', '本選挙進出'), ('accepted', '立候補承諾'), ('declined', '辞退'), ('disqualified', '資格なし'), ('elected', '当選'), ('lottery', '抽選対象'), ('not_elected', '落選')], default='eligible', max_length=20),
        ),
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', '一般枠'), ('corporate', '企業枠')], max_length=20)),
                ('vote_count', models.PositiveIntegerField()),
                ('seats_remaining', models.PositiveIntegerField()),
                ('seed', models.CharField(blank=True, max_length=128)),
                ('algorithm', models.CharField(choices=[('sha256-v1', 'SHA-256 v1')], default='sha256-v1', max_length=32)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lottery_draws', to='election.election')),
            ],
        ),
        migrations.CreateModel(
            name='LotteryCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('score', models.CharField(blank=True, max_length=64)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lottery_entries', to='election.candidate')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.lotterydraw')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lotterydraw',
            constraint=models.UniqueConstraint(fields=('election', 'category'), name='unique_lottery_per_election_category'),
        ),
        migrations.AddConstraint(
            model_name='lotterycandidate',
            constraint=models.UniqueConstraint(fields=('lottery', 'candidate'), name='unique_candidate_per_lottery'),
        ),
    ]
