# Generated by Django 6.0.8 on 2026-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_alter_candidate_status_lotterydraw_lotterycandidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterparticipation',
            name='email_send_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voterparticipation',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterparticipation',
            name='token_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
