# Generated by Django 6.0.8 on 2026-09-25 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0018_electioncycle_manager_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('eligible', '被選挙人'), ('qualified', '本選挙進出'), ('accepted', '立候補承諾'), ('declined', '辞退'), ('disqualified', '資格なし'), ('elected', '当選'), ('lottery', '抽選対象'), ('not_elected', '落選')], max_length=20, verbose_name='変更前')),
                ('new_status', models.CharField(choices=[('eligible', '被選挙人'), ('qualified', '本選挙進出'), ('accepted', '立候補承諾'), ('declined', '辞退'), ('disqualified', '資格なし'), ('elected', '当選'), ('lottery', '抽選対象'), ('not_elected', '落選')], max_length=20, verbose_name='変更後')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='election.candidate', verbose_name='候補者')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='変更者')),
            ],
            options={
                'verbose_name': '候補者ステータス変更履歴',
                'verbose_name_plural': '候補者ステータス変更履歴',
                'ordering': ['-changed_at'],
            },
        ),
    ]
