# Generated by Django 6.0.8 on 2026-09-25

from django.db import migrations, models


CANDIDATE_STATUS_CHOICES = [
    ("eligible", "被選挙人"),
    ("qualified", "本選挙進出"),
    ("accepted", "立候補承諾"),
    ("delegate_recommended", "代議員推薦"),
    ("declined", "辞退"),
    ("disqualified", "資格なし"),
    ("elected", "当選"),
    ("lottery", "抽選対象"),
    ("not_elected", "落選"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0019_candidatestatuschange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=CANDIDATE_STATUS_CHOICES,
                default="eligible",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="candidatestatuschange",
            name="previous_status",
            field=models.CharField(
                choices=CANDIDATE_STATUS_CHOICES,
                max_length=20,
                verbose_name="変更前",
            ),
        ),
        migrations.AlterField(
            model_name="candidatestatuschange",
            name="new_status",
            field=models.CharField(
                choices=CANDIDATE_STATUS_CHOICES,
                max_length=20,
                verbose_name="変更後",
            ),
        ),
    ]
