# Generated by Django 6.0.8 on 2026-09-26 00:17

import django.db.models.deletion
from django.db import migrations, models


def preserve_history_references(apps, schema_editor):
    History = apps.get_model("election", "CandidateStatusChange")
    alias = schema_editor.connection.alias
    for history in History.objects.using(alias).select_related("candidate").iterator():
        History.objects.using(alias).filter(pk=history.pk).update(
            election_id=history.candidate.election_id,
            member_id=history.candidate.member_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0020_add_delegate_recommended_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatuschange',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='election.election', verbose_name='選挙'),
        ),
        migrations.AddField(
            model_name='candidatestatuschange',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='election.membersnapshot', verbose_name='会員'),
        ),
        migrations.RunPython(preserve_history_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='candidatestatuschange',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='election.candidate', verbose_name='候補者'),
        ),
    ]
