"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Production settings
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# 本番用の秘密鍵はソースコードに保存せず、環境変数から取得する。
# 未設定のまま起動した場合は、安全のため起動時にエラーにする。
SECRET_KEY = os.environ["ELECTION_SECRET_KEY"]

DEBUG = False

# カンマ区切りで指定する（例: vote.example.jp,www.vote.example.jp）。
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ["ELECTION_ALLOWED_HOSTS"].split(",")
    if host.strip()
]

# Nginxが付与するX-Forwarded-Protoを使用して、Djangoにもとの通信が
# HTTPSだったことを伝える。Nginx側でこのヘッダーを必ず上書きすること。
SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# HTTPSでの運用をブラウザに記憶させる。最初は短い値で確認し、
# 安定運用後に31536000（1年）などへ延ばすこともできる。
SECURE_HSTS_SECONDS = int(
    os.environ.get(
        "ELECTION_SECURE_HSTS_SECONDS",
        "3600",
    )
)

# 別名ホストなどからPOSTを受ける場合に、HTTPS Originをカンマ区切りで
# 指定する（例: https://vote.example.jp）。通常の同一ホストだけなら空でよい。
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "ELECTION_CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'election',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("ELECTION_DB_NAME", "election"),
        "USER": os.environ.get("ELECTION_DB_USER", "election"),
        "PASSWORD": os.environ["ELECTION_DB_PASSWORD"],
        "HOST": os.environ.get("ELECTION_DB_HOST", "localhost"),
        "PORT": os.environ.get("ELECTION_DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.environ["ELECTION_EMAIL_HOST"]

EMAIL_PORT = int(
    os.environ.get(
        "ELECTION_EMAIL_PORT",
        "465",
    )
)

EMAIL_HOST_USER = os.environ.get(
    "ELECTION_EMAIL_USER",
    "",
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "ELECTION_EMAIL_PASSWORD",
    "",
)

EMAIL_USE_SSL = (
    os.environ.get(
        "ELECTION_EMAIL_USE_SSL",
        "true",
    ).lower()
    == "true"
)

EMAIL_USE_TLS = (
    os.environ.get(
        "ELECTION_EMAIL_USE_TLS",
        "false",
    ).lower()
    == "true"
)

EMAIL_TIMEOUT = 30

DEFAULT_FROM_EMAIL = os.environ.get(
    "ELECTION_FROM_EMAIL",
    "vote@pasj.jp",
)
